swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /descuento_matricula/:
    get:
      tags:
      - descuento_matricula
      description: get DescuentoMatricula
      operationId: DescuentoMatriculaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DescuentoMatricula'
        "403":
          description: ""
    post:
      tags:
      - descuento_matricula
      description: create DescuentoMatricula
      operationId: DescuentoMatriculaController.Post
      parameters:
      - in: body
        name: body
        description: body for DescuentoMatricula content
        required: true
        schema:
          $ref: '#/definitions/models.DescuentoMatricula'
      responses:
        "201":
          description: '{int} models.DescuentoMatricula'
        "403":
          description: body is empty
  /descuento_matricula/{id}:
    get:
      tags:
      - descuento_matricula
      description: get DescuentoMatricula by id
      operationId: DescuentoMatriculaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DescuentoMatricula'
        "403":
          description: :id is empty
    put:
      tags:
      - descuento_matricula
      description: update the DescuentoMatricula
      operationId: DescuentoMatriculaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for DescuentoMatricula content
        required: true
        schema:
          $ref: '#/definitions/models.DescuentoMatricula'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DescuentoMatricula'
        "403":
          description: :id is not int
    delete:
      tags:
      - descuento_matricula
      description: delete the DescuentoMatricula
      operationId: DescuentoMatriculaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
  /tipo_descuento_matricula/:
    get:
      tags:
      - tipo_descuento_matricula
      description: get TipoDescuentoMatricula
      operationId: TipoDescuentoMatriculaController.Get All
      parameters:
      - in: query
        name: query
        description: Filter. e.g. col1:v1,col2:v2 ...
        type: string
      - in: query
        name: fields
        description: Fields returned. e.g. col1,col2 ...
        type: string
      - in: query
        name: sortby
        description: Sorted-by fields. e.g. col1,col2 ...
        type: string
      - in: query
        name: order
        description: Order corresponding to each sortby field, if single value, apply
          to all sortby fields. e.g. desc,asc ...
        type: string
      - in: query
        name: limit
        description: Limit the size of result set. Must be an integer
        type: string
      - in: query
        name: offset
        description: Start position of result set. Must be an integer
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDescuentoMatricula'
        "403":
          description: ""
    post:
      tags:
      - tipo_descuento_matricula
      description: create TipoDescuentoMatricula
      operationId: TipoDescuentoMatriculaController.Post
      parameters:
      - in: body
        name: body
        description: body for TipoDescuentoMatricula content
        required: true
        schema:
          $ref: '#/definitions/models.TipoDescuentoMatricula'
      responses:
        "201":
          description: '{int} models.TipoDescuentoMatricula'
        "403":
          description: body is empty
  /tipo_descuento_matricula/{id}:
    get:
      tags:
      - tipo_descuento_matricula
      description: get TipoDescuentoMatricula by id
      operationId: TipoDescuentoMatriculaController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDescuentoMatricula'
        "403":
          description: :id is empty
    put:
      tags:
      - tipo_descuento_matricula
      description: update the TipoDescuentoMatricula
      operationId: TipoDescuentoMatriculaController.Put
      parameters:
      - in: path
        name: id
        description: The id you want to update
        required: true
        type: string
      - in: body
        name: body
        description: body for TipoDescuentoMatricula content
        required: true
        schema:
          $ref: '#/definitions/models.TipoDescuentoMatricula'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.TipoDescuentoMatricula'
        "403":
          description: :id is not int
    delete:
      tags:
      - tipo_descuento_matricula
      description: delete the TipoDescuentoMatricula
      operationId: TipoDescuentoMatriculaController.Delete
      parameters:
      - in: path
        name: id
        description: The id you want to delete
        required: true
        type: string
      responses:
        "200":
          description: '{string} delete success!'
        "403":
          description: id is empty
definitions:
  models.DescuentoMatricula:
    title: DescuentoMatricula
    type: object
    properties:
      Autorizado:
        type: boolean
      Descuento:
        type: number
        format: double
      Enlace:
        type: integer
        format: int64
      Ente:
        type: integer
        format: int64
      Id:
        type: integer
        format: int64
      Metadatos:
        type: string
      TipoDescuentoMatricula:
        $ref: '#/definitions/models.TipoDescuentoMatricula'
  models.TipoDescuentoMatricula:
    title: TipoDescuentoMatricula
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
tags:
- name: descuento_matricula
  description: |
    DescuentoMatriculaController operations for DescuentoMatricula
- name: tipo_descuento_matricula
  description: |
    TipoDescuentoMatriculaController operations for TipoDescuentoMatricula
